site:
  about:
    siteName: Plume
    siteDescription: Plume is a code property graph analysis library with options to extract the CPG from Java bytecode and store the result in various graph databases.
Editorial:
  primaryColor: '#00bdd6'
  legacySearch: false
  metaComponents:
    - type: 'orchidSearch'
  social:
    github: 'plume-oss/plume'
  menu:
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'

kotlindoc:
  sourceDirs:
    - './../../main/kotlin'

services:
  publications:
    stages:
      - type: 'githubPages'
        username: 'DavidBakerEffendi' # the username which created the personal access token
        repo: 'plume-oss/plume' # the repo to publish to